use csb;
select * from customer limit 20;

# Q1. what is the total revenue generated by male vs. female customers?
select gender, sum(purchase_amount) as revenue from customer group by gender;

# Q2. which customers used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount
from customer
where discount_applied = 'yes' 
	and purchase_amount >= (select avg(purchase_amount) 
    from customer);	
 select * from customer;


# Q3. which are the top 5 products with the highest average review rating?
select item_purchased, Round(avg(CAST(review_rating as decimal(10,2))), 2) as "Average prodect rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;


# Q4. compare the average purchase amount between standard and express shipping.
select shipping_type, avg(purchase_amount)
from customer
where shipping_type in ('standard', 'express')
group by shipping_type;


# Q5. do subscribe customer spend more? compare average spend and total revenue between subscribers and non-subscribers?
select subscription_status,
count(customer_id) as total_customers,
round(avg(purchase_amount), 2) as avg_spend,
round(sum(purchase_amount), 2) as total_revenue
from customer
group by subscription_status
order by total_revenue, avg_spend desc;


# Q6. which 5 product have the highest percentage of purchase with discount applied?
select item_purchased, 
round(avg(case when discount_applied = 'yes' then 1 else 0 end) * 100,2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;


# Q7. segment customer into new, returning, and loyal based on their total number of pervious purchases, 
-- and show the count of each segment.

select 
	case
		when previous_purchases = 1 then 'new'
		when previous_purchases between 2 and 10 then 'returning'
		else 'loyal'
    end as customer_segment,
	
    count(*) as customer_count
from customer 
group by customer_segment
order by customer_count desc;


# Q8. what are the top 3 most purcahsed product within each category?

select category, item_purchased, total_purchases
from(
	select
		category, item_purchased, 
        count(*) as total_purchases, 
        row_number() over (
			partition by category
            order by count(*) desc
            ) as rank_in_category
		from customer
        group by category, item_purchased
	) t
	where rank_in_category <= 3;
    
# Q.9 Are customers who are repeat buyers (more than 5 pervious purchases) also likely to subscribe?

select subscription_status, 
count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5 
group by subscription_status;

# Q10. What is the revenue contribution of each age group?

select age_group,
sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;

